tests/run-tests.sh

when calling the run-tests.sh script from a remote session modules are not loadable
sourcing /etc/profile at the beginning of the test script will allow the modules to be used

load modules when called from a remote session

---

centos/centos-7.x/centos-7.6-hpc/configure_selinux.sh
centos/centos-7.x/centos-7.7-hpc/configure_selinux.sh
centos/centos-8.x/centos-8.1-hpc/configure_selinux.sh
centos/common/configure_selinux.sh

Disable selinux on all CentOS images to avoid thorny security challenges, such as setting up shared /home directories in HPC clusters.

disable selinux

---

centos/centos-7.x/centos-7.6-hpc/README.md
centos/centos-7.x/centos-7.6-hpc/install.sh
centos/centos-7.x/centos-7.7-hpc/README.md
centos/centos-7.x/centos-7.7-hpc/install.sh
centos/centos-7.x/centos-7.8-hpc/README.md
centos/centos-7.x/centos-7.8-hpc/install.sh
centos/centos-8.x/centos-8.1-hpc/README.md
centos/centos-8.x/centos-8.1-hpc/install.sh
common/install_hpcdiag.sh
tests/run-tests.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/README.md
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install.sh

This PR adds a script called install_hpcdiag.sh to the common directory.
The script is called by each install.sh, and when invoked it fetches the latest release of the Azure HPC Diagnostics Tool from GitHub and copies it to /opt/azurehpc/diagnostics.
This branch has been run through the testing pipeline.

Adds Azure HPC Diagnostics Tool

---

centos/centos-7.x/centos-7.6-hpc/install.sh
centos/centos-7.x/centos-7.7-hpc/install.sh
centos/centos-7.x/centos-7.8-hpc/install.sh
centos/centos-8.x/centos-8.1-hpc/install.sh

Disabling Nvidia Cuda Install for CentsOS 8.1, 7.8, 7.7, 7.6 and Ubuntu 18.04.

Disabling Nvidia Cuda Install

---

centos/centos-7.x/centos-7.6-hpc/install.sh
centos/centos-7.x/centos-7.7-hpc/install.sh
centos/centos-7.x/centos-7.8-hpc/install.sh
centos/centos-8.x/centos-8.1-hpc/install.sh
centos/common/network-config.sh

RougueWave/OpenLogic CentOS NetworkManager will dynamically configure all eth network adapters. On the IB device (typically eth1) this will cause a 30s delay as the address update times out and will delay the VM provisioning - affecting TDPR.

skip IB eth device config, avoid 30s timeout

---

centos/centos-8.x/centos-8.3-hpc/README.md
centos/centos-8.x/centos-8.3-hpc/hpc-tuning.sh
centos/centos-8.x/centos-8.3-hpc/install.sh
centos/centos-8.x/centos-8.3-hpc/install_amd_libs.sh
centos/centos-8.x/centos-8.3-hpc/install_gcc.sh
centos/centos-8.x/centos-8.3-hpc/install_intel_libs.sh
centos/centos-8.x/centos-8.3-hpc/install_mellanoxofed.sh
centos/centos-8.x/centos-8.3-hpc/install_mpis.sh
centos/centos-8.x/centos-8.3-hpc/install_utils.sh
centos/centos-8.x/centos-8.3-hpc/set_properties.sh
centos/common/network-config.sh
tests/run-tests.sh

Adding support for CentOS 8.3.
Updating permissions on /centos/common/network-config.sh
Tested on Standard_HC44rs.
Notes - Kernel should be updated to the latest version because the default repo only contains kernel-devel for the latest kernel version.

Adding support for CentOS 8.3

---

centos/centos-7.x/centos-7.6-hpc/install.sh
centos/centos-7.x/centos-7.7-hpc/install.sh
centos/centos-7.x/centos-7.8-hpc/install.sh
centos/centos-7.x/common/install_utils.sh
centos/centos-8.x/centos-8.1-hpc/install.sh
centos/centos-8.x/centos-8.3-hpc/install.sh
centos/centos-8.x/common/install_utils.sh
common/install_azure_persistent_rdma_naming.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install_utils.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install_utils.sh

Only manually tested on 7.7 and 7.8.  Do we have automation for all platforms?

Fix persistent rdma naming

---

common/install_nccl.sh
common/install_nvidiagpudriver.sh
common/kernel-update.sh
tests/run-tests.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install_mellanoxofed.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install_mpis.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install_nvidiagpudriver.sh

Updated NVIDIA Driver to 460.32.03, NVIDIA Fabric Manager to 460.32.03 and CUDA to 11.2.2_460.32.03; Updated Mellanox OFED to 5.2-2.2.0.0 and HPCX to v2.8.1-gcc-MLNX_OFED_LINUX-5.2-2.2.0.0; Removed Kernel Update Script; Updated Tests; Changed NCCL Tests folder from /opt/microsoft to /opt.

Updated NVIDIA, MOFED and HPCX versions for Ubuntu 18.04

---

centos/centos-7.x/centos-7.9-hpc/README.md
centos/centos-7.x/centos-7.9-hpc/hpc-tuning.sh
centos/centos-7.x/centos-7.9-hpc/install.sh
centos/centos-7.x/centos-7.9-hpc/install_amd_libs.sh
centos/centos-7.x/centos-7.9-hpc/install_dcgm.sh
centos/centos-7.x/centos-7.9-hpc/install_gcc.sh
centos/centos-7.x/centos-7.9-hpc/install_intel_libs.sh
centos/centos-7.x/centos-7.9-hpc/install_mellanoxofed.sh
centos/centos-7.x/centos-7.9-hpc/install_mpis.sh
centos/centos-7.x/centos-7.9-hpc/install_nccl.sh
centos/centos-7.x/centos-7.9-hpc/install_nvidiagpudriver.sh
centos/centos-7.x/centos-7.9-hpc/install_utils.sh
centos/centos-7.x/centos-7.9-hpc/set_properties.sh
common/network-tuning.sh
tests/run-tests.sh

Adding the installation scripts for following libs for CentOS 7.9
- Mellanox OFED
- Pre-configured IPoIB (IP-over-InfiniBand)
- Popular InfiniBand based MPI Libraries
- HPC-X
- IntelMPI
- MVAPICH2
- OpenMPI
- Communication Runtimes
- Libfabric
- OpenUCX
- Optimized librares
- AMD BLIS
- AMD FFTW
- AMD Flame
- Intel MKL
- GPU Drivers
- Nvidia GPU Driver
- NCCL
- NCCL RDMA Sharp Plugin
- NCCL Tests
- NV Peer Memory (GPU Direct RDMA)
- GRD Copy
- Data Center GPU Manager
- Azure HPC Diagnostics Tool
Testing :
These scripts have been tested on CentOS 7.9.2009 Gen2 by OpenLogic on Standard ND96asr_v4.
Notes :
1. Right now all the scripts lives in CentOS 7.9 directory. Therefore as part of code clean and merging we should pull the common code out to common directories.
2. The code is specific to …

Adding Scripts for CentOS 7.9

---

centos/centos-7.x/centos-7.9-hpc/disable_cloudinit.sh
centos/centos-7.x/centos-7.9-hpc/install.sh

CentOS 7.9 disabling cloud-Init and removing hardware Mac address and DHCP name for eth0.

Disabling Cloud Init and Removing H/W Mac Address and DHCP Name

---

ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install_nvidiagpudriver.sh

The cuda drivers are installed via nvidia's ".run" script; whereas, the fabric manager is installed via the deb packages.  This means that if you run `apt-get upgrade`, `apt-get update`, the fabric manager and drivers will not be in sync, and you will get a cuda initialization error.  So, this change tries to fix this issue.

hold nvidia-fabricmanager version

---

tests/run-tests.sh
ubuntu/common/disable_auto_upgrade.sh
ubuntu/common/hpc-tuning.sh
ubuntu/common/install_nccl.sh
ubuntu/common/install_nvidiagpudriver.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/disable_auto_upgrade.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install_mellanoxofed.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install_mpis.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install_nvidiagpudriver.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install_mellanoxofed.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install_mpis.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install_nvidiagpudriver.sh

ubuntu driver updates; update MOFED 5.4-1.0.3.0; Update HPC-X 2.9.0 MOFED 5.4-1.0.3.0; fixed bugs; Set GoalStatePeriod to 120; Removed custom waagent; Holding auto updates for nvidia-fabricmanager and cuda drivers

Driver updates, bug fixes for ubuntu 18.04, 20.04 images

---

centos/centos-7.x/centos-7.9-hpc/clear_history.sh
centos/centos-7.x/centos-7.9-hpc/install.sh

Adding clear history script for CentOS 7.9
- will need to uncomment line 67 in centos/centos-7.x/centos-7.9-hpc/install.sh when running on VM
- can also uncomment line 12 in centos/centos-7.x/centos-7.9-hpc/clear_history.sh to remove the root bash history
Testing
The scripts were tested on CentOS 7.9 Gen2 by Rogue Wave (OpenLogic) on Standard ND96asr_v4.

Adding clear history for CentOS 7.9

---

centos/centos-7.x/common/install_dcgm.sh
centos/centos-7.x/common/install_nvidiagpudriver.sh
centos/common/install_nccl.sh
common/install_nvidiagpudriver.sh
ubuntu/common/install_dcgm.sh
ubuntu/common/install_nccl.sh
ubuntu/common/install_nvidia_fabric_manager.sh
ubuntu/common/install_nvidiagpudriver.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install_dcgm.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install_nvidiagpudriver.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install_nvidiagpudriver.sh

**Driver updates**
> NVIDIA - 495.29.05
> CUDA - 11.5.0
> NCCL - 2.11.4-1
> DCGM - 2.3.1

nvidia driver 495.29.05, CUDA 11.5.0, NCCL v2.11.4-1, DCGM 2.3.1 update for Ubuntu 18.04, 20.04 and CentOS 7.9

---

common/install_nvidiagpudriver.sh

Currently, when basing an image on the CentOS-HPC image and one installs any kernel models, the NVIDIA drivers have to be reinstalled.
Installing the drivers with dkms solves this problem.

Add --dkms to NVIDIA driver run file

---

centos/centos-7.x/centos-7.9-hpc/clear_history.sh
centos/centos-7.x/common/install_docker.sh
centos/common/install_nccl.sh
ubuntu/common/clear_history.sh
ubuntu/common/hpc-tuning.sh
ubuntu/common/install_docker.sh
ubuntu/common/install_nccl.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-LTS-hpc/install.sh

- Skip NIC renaming for Ubuntu 18.04 Images with MOFED-LTS
- Clear debris in /tmp/ and /root/
- Clear machine ID before deprovisioning
- Remove unwanted repositories and installation files
- Updated WALinuxAgent to 2.5.0.2 for Ubuntu Images

Skip rdma renaming for Ubuntu LTS; Clear unwanted files; Update waagent v2.5.0.2 for Ubuntu

---

ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install.sh

Rolling back the naming change because it causes problems in some instances.

rolling back ib naming fix

---

azure-pipelines.yml
azure-pipelines/queue_ado.sh

Added an AzDo pipeline with a PR trigger. This pipeline will submit a POST request to queue the AzDo image validation pipeline.
The pipeline with the PR trigger is defined in GitHub but runs in the Azure DevOps project that is linked w/ the GitHub repo. This pipeline queues a build for another pipeline in the same DevOps project and waits for completion of the AzDo build (throws an error if the build failed).

Add Az Pipelines for PR Trigger

---

azure-pipelines.yml
azure-pipelines/queue_ado.sh

Added some safeguards to mitigate common pipeline run failures. 
- Abort pipeline run if queue request fails (POST returns anything but response code 200).
- Increase job timeout to 6hrs
- Switch to 1ES hosted pool

Add Safeguards to Az Pipeline 

---

tests/run-tests.sh
ubuntu/common/install_nccl.sh
ubuntu/common/install_nvidia_fabric_manager.sh
ubuntu/common/install_nvidiagpudriver.sh
ubuntu/common/install_utils.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-LTS-hpc/install.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install_utils.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install_utils.sh

There are several changes in this update.
1. The nvidia gpu driver and fabric manager were updated to 510.85.02 to fix an infoROM corruption issue.
2. The nccl version as updated to 2.14.3-1 to deal with a change in the
nccl-tests.
3. The apt installs from the ubuntu install_utils.sh files were pulled out to a ubuntu/common install_utils.sh file.
Also the RELAXED_ORDERING setting was removed from the run-tests.sh file as it is not aplicable to all SKUs.

Updated nvidia gpu driver to 510.85.02

---

common/copy_test_file.sh
tests/health_checks/NDv4/ecc-errors.sh
tests/health_checks/NDv4/test-bandwidth.sh

Adding back compilation of gpu-copy executable at vm setup just so the health checks are completely setup when intallation completes. Also fixing a small bug in the ecc-errors script and making an error message created by the test-bandwidth more clear.

Fix several issues with health-checks

---

ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install_rocm.sh

Updating rocm startup service to not modprobe amdgpu if the correct number of GPUs is not detected.

Updating rocm startup service

---

README.md
alma/alma-8.x/common/install_nvidiagpudriver.sh
centos/common/install_nccl.sh
ubuntu/common/install_nv_peer_memory.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-LTS-hpc/install_mpis.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install_mellanoxofed.sh

* fix for systemd-modules-load service failing on boot
* installation directory structuring for nv peer mem
* load nvidia_peermem (GPU driver) instead of nv_peer_mem for alma
* IMPI 2021 update for Ubuntu LTS
* Badge update for alma 8.6
* Release tag NCCL for CentOS 7.9

Image health fixes and other minor improvements (#174)

---

alma/alma-8.x/alma-8.6-hpc/install.sh
alma/alma-8.x/alma-8.6-hpc/install_lustre_client.sh
ubuntu/common/hpc-tuning.sh
ubuntu/common/install_docker.sh
ubuntu/common/install_lustre_client.sh
ubuntu/common/install_utils.sh
ubuntu/common/setup_lustre_repo.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-LTS-hpc/install.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-LTS-hpc/install_utils.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install.sh

This change adds packages for Lustre for Ubuntu 18.04, 20.04, and Alma 8.6.  Alma is disabled and untested for now.
Manual testing of the new 18.04 and 20.04 scripts against a Lustre cluster indicate that they work.

Add Lustre clients to the images.

---

tests/run-tests.sh
ubuntu/common/install_dcgm.sh
ubuntu/common/install_docker.sh
ubuntu/common/install_intel_libs.sh
ubuntu/common/install_mpis.sh
ubuntu/common/install_nccl.sh
ubuntu/common/install_nvidia_fabric_manager.sh
ubuntu/common/install_nvidiagpudriver.sh
ubuntu/common/install_utils.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-LTS-hpc/install.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-LTS-hpc/install_nccl.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-LTS-hpc/install_nvidiagpudriver.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-LTS-hpc/install_utils.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install_mpis.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install_nvidiagpudriver.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install_utils.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install_mellanoxofed.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install_mpis.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install_nvidiagpudriver.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install_utils.sh

Ubuntu 20.04 HPC component configuration for H100
Component Current Version Latest available
azcopy 10.12.2 10.17.0
Mellanox OFED 5.6-1.0.3.3 5.9-0.5.6.0
HPC-x 2.11 2.14.0
MVAPICH2 2.3.7 2.3.7
OpenMPI 4.1.3 4.1.4
IMPI 2021 2021.7.0 2021.8.0
NVIDIA 520.61.05 525.85.12
CUDA 11.8 12.0
NV peer memory 1.3.0 1.3.0
GDR Copy 2.3 2.3
NCCL 2.15.1-1 2.16.5-1
DCGM 2.4.4 3.1.6
Intel One MKL 2022.1.0.223 2023.0.0

H100 20.04 HPC component updates

---

alma/alma-8.x/alma-8.7-hpc/install.sh
alma/alma-8.x/alma-8.7-hpc/install_amd_libs.sh
alma/alma-8.x/alma-8.7-hpc/install_mpis.sh
alma/alma-8.x/common/install_utils.sh
common/install_health_checks.sh

- HPC-x v2.15 fix
- Disabling additional dependencies on kernel-core
- Minor bug fixes pertaining to health checks

HPC-x v2.15 fix for AlmaLinux HPC 8.7

---

common/install_health_checks.sh

- update of AZ NHC which replaces old IB loop back method so that HCA's now communicate to themselves vs a pair of HCA's communicating.
- https://github.com/Azure/azurehpc-health-checks/releases/tag/v0.2.6

AZ NHC version update

---

alma/common/hpc-tuning.sh
ubuntu/common/hpc-tuning.sh

This was broken as it was split on multiple lines.  This caused errors for the first three and then applied the read ahead to every device. The way the file was written also meant that `$kernel` and `$4` were evaluated by the shell when writing the file as the $'s needed to be escaped.

fixed udev rules for nfs-readahead

---

tests/run-tests.sh

remove all docker containers after testing docker.
the hello-world containers left over from testing may trigger security policy violation.

remove all containers after testing docker

---

topology/ncv4-topo.xml

The GPU values for NUMA domains 1 and 2, 3 and 4, were swapped. Corrected the values and "unswapped" them. 
Ran NCCL and verified that there were no errors related to the change in topo file. Attached the results as a .txt file.
[ncv4-topo-swap-test.txt](https://github.com/Azure/azhpc-images/files/14289622/ncv4-topo-swap-test.txt)

fix swapped values in ncv4 topo file

---

alma/alma-8.x/alma-8.7-hpc/install_mpis.sh
tests/run-tests.sh
ubuntu/common/install_mpis.sh

The OSU Benchmarks were not in the directory where HPC-X was rebuilt with PMIx. Copied the test directory and adjusted the unit tests to catch this case.

copy hpcx tests to hpcx-rebuild

---

alma/alma-8.x/alma-8.7-hpc/install_mpis.sh
tests/run-tests.sh
ubuntu/common/install_mpis.sh

The HPC-X rebuild directory was missing files needed to run MPI benchmarks.

Include orte in the HPC-X rebuild

---

alma/alma-8.x/alma-8.7-hpc/install_mpis.sh

The module files directory wasn't defined when referenced during MPI installation

add the modulefiles directory in alma

---

tests/run-tests.sh

'hello-world' container image which is left over from docker testing can be flagged by security scanner. it is not needed in the image and should be removed

cleanup hello-world docker image

---

common/setup_sku_customizations.sh

NCv4 topo file and graph file is applicable only for the NCv4 96-core VM size. Smaller sizes dont need topo/graph file.

Update SKU Customizations for NCv4

---

common/clear_history.sh

delete the ssh authorized keys in the cleanup script run before generalizing the VM

delete ssh authorized keys

---

alma/common/install_mpis.sh
common/install_amd_libs.sh
ubuntu/common/install_mpis.sh
versions.json

- Update DOCA, HPC-X, MVAPICH2, and IMPI
- Fix Ubuntu OpenMPI installation to use HCOLL and UCX bundled with the HPC-X

Update UCX related components and reference bug

---

tests/test-definitions.sh

We've run into cases where ibstat shows the infiniband devices, but ifconfig does not. Since this is a bad configuration and will cause issues, we should test ifconfig as well

Add ifconfig check to tests

---

alma/common/install_mpis.sh
ubuntu/common/install_mpis.sh
versions.json

The new azure tuned MVAPICH2 library was hanging on allreduce or alltoall. Rollback to the previous version.

rollback mvapich2

---

topology/ndv5-topo.xml

- The CPU affinity mask was flipped wrt NUMA domain.

Corrected CPU range/affinity mask on NDv5 topo file.

---

common/setup_sku_customizations.sh
customizations/ncv4.sh
customizations/ndv2.sh
customizations/ndv4.sh
customizations/ndv4_rocm.sh
customizations/ndv5.sh
customizations/ndv5_rocm.sh

- Modify ND and NCv4 sku customization scripts to add "NCCL_IGNORE_CPU_AFFINITY=1" to the nccl.conf file
- Remove unutilized code from the custimization files
- Put NVME disk setop commands as place holders for AMD SKU customization in place of nccl.conf creation

Add NCCL_IGNORE_CPU_AFFINITY flag to nccl conf. Remove useless code

---

tests/test-definitions.sh
ubuntu/ubuntu-22.x/ubuntu-22.04-hpc/install_rocm.sh

The first username created during the VM deployment was not in the render group causing the rccl test not to run

Fix render group membership

---

versions.json

Dues to some compatibility issues, we need to downgrade the rocm version to 6.2.2

Downgrade rocm version for compatibility

---

tests/run-tests.sh
tests/test-definitions.sh

Adds a flag on run-tests.sh and enables the sanity check continue to run when a single function fails, which can help understand the thorough VM status in local tests. The flag is optional.

Make sanity check continues on error

---

versions.json

Do not upgrade the hpcx and impi version for both alma8.10 and ubuntu22.04 in this coming release. 
There are two reasons: 
1. For ubuntu22.04, in our already finished ADO validation pipelines, we observed serious performance downgrade with the latest version.
2. For alma8.10, in our already finished ADO validation pipelines, we observed the images with the latest hpcx and impi are stuck in mpi benchmarks.
So, we decided to keep the legacy version of hpcx and impi.

Do not upgrade impi and hpcx
