centos/centos-7.6/hpc-tuning.sh
centos/centos-7.6/install.sh
centos/centos-7.6/install_gcc-8.2.sh
centos/centos-7.6/install_mellanoxofed.sh
centos/centos-7.6/install_mpis.sh
centos/centos-7.6/install_utils.sh
centos/centos-7.7/hpc-tuning.sh
centos/centos-7.7/install.sh
centos/centos-7.7/install_gcc-8.2.sh
centos/centos-7.7/install_mellanoxofed.sh
centos/centos-7.7/install_mpis.sh
centos/centos-7.7/install_utils.sh
centos/common/hpc-tuning.sh
centos/common/install_utils.sh
common/install_gcc-8.2.sh
common/install_mpis.sh

- Initial commit for CentOS HPC image (7.6/7.7)

CentOS HPC image

---

centos/centos-7.6-hpc/install_mellanoxofed.sh
centos/centos-7.6-hpc/install_mpis.sh
centos/centos-7.7-hpc/install_mellanoxofed.sh
centos/centos-7.7-hpc/install_mpis.sh
common/install_mpis.sh
tests/run-tests.sh

Updates include:
- Mellanox OFED 5.0-1.0.0.0
- HPC-X 2.6
- MVAPICH2 2.3.3
- MVAPICH2-X 2.3.rc3
- Intel MPI 2019 Update 6
- OpenMPI 4.0.3
- Add basic validation script

Image updates

---

centos/centos-7.x/centos-7.6-hpc/configure_selinux.sh
centos/centos-7.x/centos-7.7-hpc/configure_selinux.sh
centos/centos-8.x/centos-8.1-hpc/configure_selinux.sh
centos/common/configure_selinux.sh

Reverts Azure/azhpc-images#18
Reverting the PR after discussing with @mvrequa

Revert "disable selinux"

---

centos/centos-7.x/centos-7.8-hpc/README.md
centos/centos-7.x/centos-7.8-hpc/hpc-tuning.sh
centos/centos-7.x/centos-7.8-hpc/install.sh
centos/centos-7.x/centos-7.8-hpc/install_amd_libs.sh
centos/centos-7.x/centos-7.8-hpc/install_gcc.sh
centos/centos-7.x/centos-7.8-hpc/install_intel_libs.sh
centos/centos-7.x/centos-7.8-hpc/install_lustre_client.sh
centos/centos-7.x/centos-7.8-hpc/install_mellanoxofed.sh
centos/centos-7.x/centos-7.8-hpc/install_mpis.sh
centos/centos-7.x/centos-7.8-hpc/install_utils.sh
centos/centos-7.x/centos-7.8-hpc/set_properties.sh
tests/run-tests.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install_mpis.sh

- Add CentOS 7.8 HPC
- Update MPI library versions for Ubuntu

Add CentOS 7.8 HPC

---

centos/common/install_mpis.sh
tests/run-tests.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install_mpis.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install_mpis.sh

Updated MVAPICH2 to 2.3.6 for CentOS and Ubuntu; Updated changes in Test script

Updated MVAPICH2 to 2.3.6

---

centos/common/install_nccl.sh
ubuntu/common/install_nccl.sh

The changes have been tested on NDv4 SKU CentOS 7.9 & Ubuntu 20.04.

Updating NCCL version to 2.9.9-1

---

centos/centos-7.x/centos-7.9-hpc/clear_history.sh

sync rpmdb to remove warnings from yum

yum sync history to remove rpmdb warning

---

tests/health_checks/NDv4/dcgmi-check.sh
tests/run-tests.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install_rccl.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install_rocm.sh

I would like to merge in a branch that uses the rocm software stack to enable compute on AMD GPUs. The major changes are as follows:
- Removed the cuda software stack and Nvidia driver installation
- Removed the installation of nccl and nccl tests.
- Added installation of AMD drivers and the ROCm software stack.
- Added the installation of rccl and rccl tests. 
- Added a system service that executes "sudo modprobe amdgpu" at startup.

Merge in rocm branch

---

ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install.sh

Install the moby engine in the image.

installing moby-engine

---

README.md

docs: add link to images on Azure marketplace

---

centos/centos-7.x/centos-7.9-hpc/install.sh
centos/centos-7.x/common/install_nvidiagpudriver.sh
centos/centos-7.x/common/install_utils.sh
common/setup_sku_customizations.sh
customizations/ncv4.sh
customizations/ndv2.sh
customizations/ndv4.sh
tests/run-tests.sh
ubuntu/common/install_nccl.sh
ubuntu/common/install_nvidia_fabric_manager.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-LTS-hpc/README.md
ubuntu/ubuntu-18.x/ubuntu-18.04-LTS-hpc/install.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-LTS-hpc/install_utils.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/README.md
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install_utils.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/README.md
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install_utils.sh

Co-Authored-By: Scott Moe <scottmoe@microsoft.com>

SKU specific topo file customization

---

common/copy_test_file.sh
tests/health_checks/NDv4/check-hardware.sh
tests/health_checks/NDv4/dcgmi-check.sh
tests/health_checks/NDv4/ecc-errors.sh
tests/health_checks/NDv4/gpu-copy.cu
tests/health_checks/NDv4/run-health-checks.sh
tests/health_checks/NDv4/test-MaxPayLoad.sh
tests/health_checks/NDv4/test-bandwidth.sh
tests/health_checks/NDv4/test-nccl.sh

1. The run-health-checks.sh script checks for health-checks in the local directory if a directory is not provided.
2. The ecc-errors.sh script now perform a more detailed exploration of ECC errors. An indication is provided when a large number of correctable ECC errors are occuring.
3. The check-hardware.sh script now checks if the correct number of NVME drives are attached.
4. The test-bandwidth.sh script now has the ability to compile bandwidth executable if it is not detected.
5. The test-MaxPayLoad.sh test has been added to indicate if the set MaxPayload matches the max available on the gpus.

Several changes made to the NDv4 health checks.

---

ubuntu/common/install_monitoring_tools.sh
ubuntu/common/install_utils.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install_utils.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install_utils.sh

Updating Moneo tag and ansible install

Updating Moneo tag and ansible install

---

README.md
alma/alma-8.x/common/install_nvidiagpudriver.sh
centos/common/install_nccl.sh
ubuntu/common/install_nv_peer_memory.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-LTS-hpc/install_mpis.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install_mellanoxofed.sh

- Fix for systemd-modules-load service failure due to ib_iser
- Clean directory structure for Ubuntu scripts (Sync with alma)
- Load nvidia-peermem (module from GPU driver) for AlmaLinux
- IMPI 2021 update for Ubuntu LTS
- Badge update for AlmaLinux 8.6
- Release tag for NCCL for CentOS 7.9

Image health fixes and other minor improvements

---

ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install_rocm.sh

Leaving the grub settings as default

remove extra settings from grub cmdline

---

ubuntu/common/install_nvidiagpudriver.sh

Reference - https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#ubuntu-installation

Update cuda-keyring for setting cuda repo

---

ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install_rocm.sh

Waiting 2 minutes after detecting GPUs to execute modprobe amdgpu, also making sure amdgpu is blacklisted.

Waiting 2 minutes after detecting GPUs to execute modprobe amdgpu.

---

alma/alma-8.x/alma-8.6-hpc/install.sh
alma/common/hpc-tuning.sh
common/setup_nvme.sh
common/setup_sku_customizations.sh
customizations/hbv4.sh
customizations/ncv4.sh
customizations/ndv4.sh
customizations/setup_nvme.sh
ubuntu/common/hpc-tuning.sh
ubuntu/common/install_utils.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install.sh
ubuntu/ubuntu-22.x/ubuntu-22.04-hpc/install.sh

- https://github.com/Azure/azurehpc/blob/master/experimental/deploy_cycle_slurm_ndv4/scripts/setup-nvme.sh
- https://learn.microsoft.com/en-us/azure/azure-netapp-files/performance-linux-nfs-read-ahead
- https://learn.microsoft.com/en-us/azure/storage/blobs/network-file-system-protocol-support-how-to

SKU specific nvme bring-up configuration

---

ubuntu/common/install_monitoring_tools.sh
ubuntu/common/install_utils.sh

Following changes are to incorporate the new version of Moneo to H100 Image
- Changes to common ubuntu install utils
- Changes to Monitoring tools install script

changes to incorporate new Moneo features/dependencies

---

alma/alma-8.x/common/install_nvidiagpudriver.sh
customizations/ndv5.sh
ubuntu/common/install_nvidiagpudriver.sh

- Update topology file
- Retain backward compatibility for tools using cuda-samples

Ndv5 topology file update, minor fix

---

alma/alma-8.x/alma-8.6-hpc/README.md

Added instructions for AMLFS client installation on Alma 8.6.

Add AlmaLinux 8.6 AMLFS Install Instructions

---

ubuntu/common/install_nvidiagpudriver.sh
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/README.md
ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/install_utils.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/README.md
ubuntu/ubuntu-22.x/ubuntu-22.04-hpc/README.md

- fix for apt-pkg not found
- fix kernel versions in the readme files

minor bug fixes for ubuntu systems

---

common/install_health_checks.sh

Updated release and removing non-qa'd checks

az health check update

---

tests/health_checks/NDv4/test-nccl.sh

Updating nccl buffer size to 4G.

increasing nccl size

---

alma/alma-8.x/common/install_utils.sh
alma/common/install_monitoring_tools.sh
ubuntu/common/install_monitoring_tools.sh
ubuntu/common/install_utils.sh

- Update Moneo install
- install pssh

Moneo update

---

common/setup_sku_customizations.sh

Update SKU matching pattern to allow for Standard_ND112asr_A100_v4 and Standard_ND112amsr_A100_v4

update NDV4 pattern to include more SKUs

---

alma/common/install_monitoring_tools.sh
ubuntu/common/install_monitoring_tools.sh

removed extra argument from configure as it is no longer needed

---

alma/common/install_monitoring_tools.sh
common/install_health_checks.sh
ubuntu/common/install_monitoring_tools.sh

Updated install scripts to grab latest releases of NHC and Moneo

Moneo + Az NHC update

---

requirements.json

updated the following packages:
AzHC = 0.2.6
AOCC=4.0.0-1
AOCL=4.0
Cuda=12.2.1 (ubuntu 2204 and 2004)
Intel_One_KL = 2023.2.0
Moneo=3.3
NCCL=2.19.3-1
Nvidia=535.86.10
NVIDIAFabricManager=535_535.86.10-10

Update requirements.json.  Set baseline versions.

---

common/install_utils.sh
tests/test-definitions.sh
ubuntu/common/hpc-tuning.sh
ubuntu/common/install_dcgm.sh
ubuntu/common/install_docker.sh
ubuntu/common/install_lustre_client.sh
ubuntu/common/install_utils.sh
ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/install_prerequisites.sh
ubuntu/ubuntu-22.x/ubuntu-22.04-hpc/install_prerequisites.sh

* In Ubuntu, upgrade all components (except kernel) prior to install of HPC components
* Remove slurm install for now

Upgrade all components 

---

common/install_health_checks.sh
requirements.json

- remove old install method
- pull docker image onto image

Update to AzNHC install

---

common/clear_history.sh

Add automatic confirmation to the command to remove defender

confirm defender removal

---

ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/README.md
ubuntu/ubuntu-22.x/ubuntu-22.04-hpc/README.md

Add `--bind-to numa` argument to mpirun commands.

add --bind-to numa to mpirun

---

tests/run-tests.sh
tests/test-definitions.sh
tests/test-matrix.json

Adding some tests for components we install that aren't being checked now.

Add additional tests for component installation

---

alma/common/disable_cloudinit.sh
customizations/alma_disable_cloudinit.sh

Alma 8.10 added a setting to the network configuration that caused IP issues. Removing that as well

update network configuration for Alma 8.10

---

alma/common/install_nvidiagpudriver.sh
ubuntu/common/install_nvidiagpudriver.sh
versions.json

- Update CUDA
- Fix the CUDA sample path to point to the installed CUDA version directory

updating CUDA and fixing CUDA samples path

---

README.md

Update any references to Alma 8.7 in the README to Alma 8.10

Update Alma version in README.md

---

topology/ndv2-topo.xml
topology/ndv4-topo.xml

Topo fixes for CPU affinity for NDv2/4

---

ubuntu/ubuntu-22.x/ubuntu-22.04-hpc/install_rccl.sh

Avoid Hard Coded Version

---

ubuntu/ubuntu-22.x/ubuntu-22.04-hpc/install_rocm.sh

The proposed use of udev rules to grant all users access to GPUs follows the method described [in ROCm documentation](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/prerequisites.html#grant-gpu-access-to-all-users-on-the-system).
The previous method of relying on `/etc/adduser.conf` to assign all new users to `video,render` secondary groups fails if users are not created with `adduser`. This is for example the case of users created by CycleCloud.

Use udev rule to grant AMD GPU access to all users
